    twist_topic: "/cmd_vel_mux/input/teleop"
    left_motor_topic: "/rover5/left_motor"
    right_motor_topic: "/rover5/right_motor"
    left_rpm_max: 100.0
    right_rpm_max: 100.0
    left_wheel_diameter_mm: 60.0
    right_wheel_diameter_mm: 60.0
    wheel_spacing_mm: 190.0
    pwm_limit: 255
